# Generated by Django 4.2.4 on 2023-09-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dev_profile_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="projects",
            field=models.ManyToManyField(blank=True, to="dev_profile_app.project"),
        ),
    ]
