# Generated by Django 4.2.4 on 2023-09-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dev_profile_app", "0002_developer_projects"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "developers",
                    models.ManyToManyField(blank=True, to="dev_profile_app.developer"),
                ),
                (
                    "projects",
                    models.ManyToManyField(blank=True, to="dev_profile_app.project"),
                ),
                (
                    "stacks",
                    models.ManyToManyField(blank=True, to="dev_profile_app.stack"),
                ),
                (
                    "technologies",
                    models.ManyToManyField(blank=True, to="dev_profile_app.technology"),
                ),
            ],
        ),
    ]
