# Generated by Django 4.2.4 on 2023-09-06 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dev_profile_app", "0003_alldata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="developer",
            name="projects",
        ),
        migrations.RemoveField(
            model_name="developer",
            name="stacks",
        ),
    ]
