# Generated by Django 4.2.4 on 2023-09-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dev_profile_app", "0004_remove_developer_projects_remove_developer_stacks"),
    ]

    operations = [
        migrations.AddField(
            model_name="developer",
            name="projects",
            field=models.ManyToManyField(blank=True, to="dev_profile_app.project"),
        ),
        migrations.AddField(
            model_name="developer",
            name="stacks",
            field=models.ManyToManyField(blank=True, to="dev_profile_app.stack"),
        ),
    ]
